name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  debugger:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Testing
        run: |
          echo ${{fromJson(needs.job1.outputs.matrix)}}
          echo ${{needs.job1.outputs.matrix}}
          echo ${{toJson(needs.job1.outputs.matrix)}}
  job2:
    needs: [job1, debugger]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build
