---
name: testing theories

on:
  push:
    branches:
      - 'account**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      applications: ${{ steps.output-applications.outputs.applications }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          # Branch Convention: ENV_NAME/AWS_ACCOUNT_ID/APP
          echo "ACCOUNT_NAME=$(echo ${{ github.ref }} | cut -d'/' -f3)" >> $GITHUB_ENV
          echo "ENV_NAME=$(echo ${{ github.ref }} | cut -d'/' -f4)" >> $GITHUB_ENV

      - name: output applications
        id: output-applications
        run: |
          echo "::set-output name=applications::$( jq .$ACCOUNT_NAME test.json | jq -sR '.')"

      - name: debug
        run: |
          jq .$ACCOUNT_NAME test.json | jq -sR '.'
          cat test.json
          jq .accountA test.json | jq -sR '.'

  debugger:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Testing
        run: |
          echo ${{ needs.setup.outputs.applications }}
          # echo ${{fromJSON(needs.setup.outputs.applications)}}

  theory:
    runs-on: ubuntu-latest
    needs: debugger
    strategy:
      matrix:
        application: ${{needs.setup.outputs.applications}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test my Theory
        run: |
          echo ${{ matrix.application }}
