---
name: testing theories

on:
  push:
    branches:
      - 'account**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      account: ${{ steps.output-accpimt.outputs.account }}
      environment: ${{ steps.output-accpimt.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: output account
        id: output-account
        run: |
          echo "::set-output name=account::$(echo ${{ github.ref }} | cut -d'/' -f3)"

      - name: output environment
        id: output-environment
        run: |
          echo "::set-output name=environment::$(echo ${{ github.ref }} | cut -d'/' -f4)"

  theory:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
        - {app: app-a, account: accountA}
        - {app: app-b, account: accountA}
        - {app: app-c, account: accountA}
        - {app: app-d, account: accountB}
        - {app: app-e, account: accountB}
        - {app: app-f, account: accountB}
    if: matrix.cfg.account == needs.setup.outputs.account
    steps:
      - name: Test my Theory
        run: |
          echo ${{ matrix.cfg.app }}
