---
name: testing theories

on:
  push:
    branches:
      - 'account**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      applications: ${{ steps.output-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          # Branch Convention: ENV_NAME/AWS_ACCOUNT_ID/APP
          echo "ACCOUNT_NAME=$(echo ${{ github.ref }} | cut -d'/' -f3)" >> $GITHUB_ENV
          echo "ENV_NAME=$(echo ${{ github.ref }} | cut -d'/' -f4)" >> $GITHUB_ENV

      - name: output applications
        id: output-matrix
        run: |
          echo "::set-output name=matrix::$( jq -c .$ACCOUNT_NAME test.json | jq -R '.')"

      - name: debug
        run: |
          jq -c .$ACCOUNT_NAME test.json | jq -R '.'
          cat test.json
          jq -c .accountA test.json | jq -R '.'

  debugger:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Testing
        run: |
          echo ${{ needs.setup.outputs.matrix }}

  theory:
    runs-on: ubuntu-latest
    needs: debugger
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Test my Theory
        run: |
          echo ${{ matrix.app }}
